[package]
name = "hop"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
dotenv = "0.15.0"
ratatui = "0.29.0"
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-rustls", "sqlite", "derive", "macros" ] }
tokio = { version = "1.42.0", features = ["full"] }
